name:      ArunRocks
url:       http://www.arunrock.com
slogan:    Partly Arty, Partly Geek
markdown:  rdiscount
pygments: true
permalink: pretty
tag_dir: tags
exclude: [README.markdown, Rakefile]
rdiscount
  extensions: [smart]
