name:      ArunRocks
url:       http://www.arunrocks.com
markdown:  rdiscount
pygments: true
permalink: pretty
lsi: false
tag_dir: tags
exclude: [README.markdown, Rakefile]
rdiscount
  extensions: [smart]
