# -*-ruby-*-
# Build tasks for arunrocks.com

task :default => :server

# Common tasks of running Jekyll ----------

desc 'Running Jekyll with --server --auto option'
task :server do
  system('jekyll --server --pygments --auto')
end
